version: '3.8'

services:
  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform.local
    volumes:
      - ./terraform:/terraform
    working_dir: /terraform
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}