version: '3.8'

services:
  dev_terraform:
    image: hashicorp/terraform:latest
    container_name: terraform.local
    volumes:
      - ./:/work
    working_dir: /work
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}